make po/make-pot work again
svn path=/trunk/; revision=4234

diff --git a/po/make-pot b/po/make-pot
--- a/po/make-pot
+++ b/po/make-pot
@@ -2,7 +2,7 @@
 
 # make-pot -- extract .pot file from sources
 
-# $Id$
+# $Id: make-pot,v 1.5 2000/09/01 22:45:15 john Exp $
 
 # This file is part of sawfish.
 
@@ -20,29 +20,32 @@
 # along with sawfish; see the file COPYING.  If not, write to
 # the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 
-REP_SRCS="../scripts/*.jl\
- ../themer/themer.in\
- ../themes/*/theme.jl"
+case $1 in
+	*update)
+		intltool-update --pot
+		mv -f untitled.pot sawfish.pot
+	;;
 
-REP_SRCS="$REP_SRCS `find ../lisp -name '*.jl' -print`"
+	*generate)
+		REP_SRCS="../scripts/*.jl\
+		 ../themes/*/theme.jl"
 
-GLADE_SRCS="../themer/themer.glade"
+		REP_SRCS="$REP_SRCS `find ../lisp -name '*.jl' -print`"
 
-rm -f sawfish.pot
+		rm -f sawfish.pot
 
-if [ ! -r ../DOC ]; then
-  echo "error: Need a DOC file!"
-  exit 1
-fi
+		if [ ! -r ../DOC ]; then
+  			echo "error: Need a DOC file!"
+  			exit 1
+		fi
 
-lisp_c=.$$.lisp.c
-glade_c=.$$.glade.c
+		lisp_c=.$$.lisp.c
 
-./sawfish-xgettext --doc-file=../DOC --c $REP_SRCS >$lisp_c
-libglade-xgettext --c $GLADE_SRCS >$glade_c
+		./sawfish-xgettext --doc-file=../DOC --c $REP_SRCS >$lisp_c
+		
+		xgettext --add-comments -a --no-location $lisp_c 
+		mv -f messages.po sawfish.pot
 
-xgettext --add-comments -a --no-location $lisp_c $glade_c
-mv -f messages.po sawfish.pot
-
-rm -f $lisp_c $glade_c
-
+		rm -f $lisp_c
+	;;
+esac
