use sawfish-xgettext to extract localized strings

diff --git a/po/make-pot b/po/make-pot
--- a/po/make-pot
+++ b/po/make-pot
@@ -31,14 +31,17 @@ REP_SRCS="$REP_SRCS `find ../lisp -name '*.jl' -print`"
 
 GLADE_SRCS="../themer/themer.glade"
 
-REP_XGETTEXT_FLAGS="--only-commands --include defun --include defcustom --include defgroup"
-
 rm -f sawfish.pot
+
+if [ ! -r ../DOC ]; then
+  echo "error: Need a DOC file!"
+  exit 1
+fi
 
 lisp_c=.$$.lisp.c
 glade_c=.$$.glade.c
 
-rep-xgettext --c $REP_XGETTEXT_FLAGS $REP_SRCS >$lisp_c
+./sawfish-xgettext --doc-file=../DOC --c $REP_SRCS >$lisp_c
 libglade-xgettext --c $GLADE_SRCS >$glade_c
 
 xgettext --add-comments -a --no-location $lisp_c $glade_c
